// NOTE: This file is automatically generated by the build process and should not be checked in.\n 
#define KVERSION "Error opening verion file: kohi.core\version.txt. Using a default version of 0.0.0.0.0.0.25201-62539" 
